---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: ghost
  namespace: demo
  annotations:
    flux.weave.works/tag.chart-image: glob:2.23.*
    flux.weave.works/automated: 'true'
spec:
  releaseName: ghost
  chart:
    git: https://github.com/xyzxyzxyzxyzxyz/flux-get-started.git
    ref: master
    path: charts/ghost
  values:
    image: bitnami/ghost:2.23.4
    persistence:
      enabled: false
    resources:
      requests:
        memory: 32Mi
        cpu: 10m
    serviceType: ClusterIP
    mariadb:
      persistence:
        enabled: false
